### ISSUE TITLE
An error was caused while dragging the tabs.

### ISSUE THREAD

**Issue by XSH-Hero** [files-community/files-uwp#1949] opened 2020-09-20 15:40 UTC
When I dragged the tab (which I wasn't on ) out of the main window, it won't create a new window, actually, it crash.

**Comment by XSH-Hero** [comment] 2020-09-20 15:41
- OS Version: [Windows 10 2004 20211.1000]
 - App version: [v0.14.0]

**Comment by XSH-Hero** [comment] 2020-09-20 15:41
This is the log:
2020-09-20 23:27:03.9423|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
   at Files.UserControls.HorizontalMultitaskingControl.<TabStrip_TabDroppedOutside>d__21.MoveNext() + 0xf4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_11[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x133e7a0

**Comment by XSH-Hero** [comment] 2020-09-20 15:49
The error behaves lik this:
![image](https://user-images.githubusercontent.com/69738882/93715454-e5ac5300-fb9b-11ea-85af-0ca67b870e56.png)

**Comment by Thomas1664** [comment] 2020-09-20 15:51
Duplicate of #1875

**Closed** 2020-09-21 03:07 UTC
Labels: bug, needs-triage
