### ISSUE TITLE
Reorder Sidebar

### ISSUE THREAD

**Issue by jdcarmack** [files-community/files-uwp#1324] opened 2020-07-01 18:49 UTC
**Describe the bug**
There does not seem to be a way to reorder items that are pinned to the sidebar. 

**To Reproduce**
1. Go to Side Bar

**Expected behavior**
The most intuitive way would be to drag and drop pinned items up and down the sidebar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by XPoppyX** [comment] 2020-07-01 22:05
@yaichenbaum isn't it a duplicate of #1069 ?

**Comment by yaichenbaum** [comment] 2020-07-01 22:34
Merging with #1069.

**Closed by yaichenbaum** 2020-07-01 22:34 UTC
Labels: bug, triage approved
