### ISSUE TITLE
It could not show the shortcut.

### ISSUE THREAD

**Issue by 1426652334** [files-community/files-uwp#1002] opened 2020-06-11 10:28 UTC
**Describe the bug**
It could not show the shortcut.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18363.900]
 - App version: [v0.9.2.0]

**Comment by XPoppyX** [comment] 2020-06-11 11:24
The app doesn't support shortcuts yet

**Comment by duke7553** [comment] 2020-06-18 09:34
Duplicate of #177

**Closed by duke7553** 2020-06-18 09:34 UTC
Labels: bug, needs-triage
