### ISSUE TITLE
Some suggestions to improve user experience

### ISSUE THREAD

**Issue by 7xavierl** [files-community/files-uwp#1553] opened 2020-07-23 17:08 UTC
**OS: Windows 10 v1909**
**Files UWP Versoin: 0.12.0.0**
**Using Dark Theme and Desktop Layout**

After using it for about a few days, i'd like to make some suggestions to improve the user experience.
First of all, the drag and drop feature. Right now, you have to click on the item (select it) then you can drag and drop it evrerywhere. On the traditional file explorer, you do not need to select the file before dragging it aroud. It's a simple detail, but would improve a lot the user experience with this tool.

The seccond suggestion lays on the archives details. On the traditional file explorer, you can enable details to be shown when you selec a file. It creates a section on the right side os the explorer includind a preview of the file (very usefull if it is an image) and some details like creation date, las modification date, extention... Things that might be important for some users.

Third one, the "My Computer" folder. The "Drives" section is not a bad idea, but i do miss the option to right click on "my computer" and go to proprieties. Also, for users that have a lot of drives and depend on monitoring the free space on them, would be usefull to have that information easy to look, just like we have in the "my computer" folder.

As far from that, i think you guys are doing an amazing work and i love how this project is going. The desing is so beautifull.
Keep on the good work! I hope my suggestions can help make the software even better.

**Comment by XPoppyX** [comment] 2020-07-29 13:05
> the drag and drop feature. Right now, you have to click on the item (select it) then you can drag and drop it evrerywhere. On the traditional file explorer, you do not need to select the file before dragging it aroud. It's a simple detail, but would improve a lot the user experience with this tool.

Duplicate of #673 



> The seccond suggestion lays on the archives details. On the traditional file explorer, you can enable details to be shown when you selec a file. It creates a section on the right side os the explorer includind a preview of the file (very usefull if it is an image) and some details like creation date, las modification date, extention... Things that might be important for some users.

Duplicate of #130 


 


> for users that have a lot of drives and depend on monitoring the free space on them, would be usefull to have that information easy to look, just like we have in the "my computer" folder.

#366

**Closed** 2020-08-06 01:09 UTC
Labels: duplicate, enhancement
