### ISSUE TITLE
can't copy file name when we rename it[even useing ctrl+c,it doesn't work]

### ISSUE THREAD

**Issue by qw1085209368** [files-community/files-uwp#1486] opened 2020-07-17 08:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment] 2020-07-17 11:01
Duplicate of #1381

**Closed** 2020-07-17 12:09 UTC
Labels: bug, enhancement, needs-triage
