### ISSUE TITLE
CTRL+X,CTRL+C or CTRL+V aka Copy Paste functionality broken

### ISSUE THREAD

**Issue by Xemanth** [files-community/files-uwp#1248] opened 2020-06-26 10:04 UTC
Keyboard shortcuts for copying and pasting are not working :(
CTRL+X
CTRL+C
CTRL+V

OS: Win 10 Pro x64 build 20150 (Insider Dev Channel)
APP: 0.10.2.0

**Comment by XPoppyX** [comment] 2020-06-26 12:00
in my case it is difficult to make them work, copy / paste and check "delete permanently",
it's like it requires some specific timing for them to work: #963

**Comment by duke7553** [comment] 2020-06-26 17:51
Thank you for reporting this. While we work on the fix, I'm going to move this item into #963 .

Duplicate of #963

**Closed by duke7553** 2020-06-26 17:51 UTC
Labels: bug, needs-triage
