### ISSUE TITLE
Add new tab bug

### ISSUE THREAD

**Issue by X-Jackdaw** [files-community/files-uwp#1741] opened 2020-08-15 09:52 UTC
**Describe the bug**
The application crashed when adding a new tab.

**To Reproduce**
1. Go to 'settings' 
2. Close the experimental function _**Show mulitasking flyout in the navigation toolbar**_
3. Go back and click the add new tab button

**Screenshots**
![2020-08-15 17-38-33](https://user-images.githubusercontent.com/48050957/90309943-967d5d80-df1f-11ea-9e28-45ee468e35c1.gif)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004 19041.450
 - App version: v0.13.0.0

**Additional context**
Log:
[debug.txt](https://github.com/files-community/files-uwp/files/5078446/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5078447/debug_fulltrust.txt)

**Comment by XPoppyX** [comment] 2020-08-15 12:02
Duplicate of #1641

**Closed** 2020-08-16 02:26 UTC
Labels: bug, duplicate
