### ISSUE TITLE
All disks are not visisble 

### ISSUE THREAD

**Issue by Alb97** [files-community/files-uwp#1156] opened 2020-06-20 05:31 UTC
**Describe the bug**
The are not all disks in a list of disks

**To Reproduce**
Open application
One drive and two disks are presented. 

**Expected behavior**
All disks should be visible. 
**Screenshots**
<img width="223" alt="Снимок" src="https://user-images.githubusercontent.com/32934166/85192943-7178bf80-b2cd-11ea-99b5-24a0d0b93119.PNG">

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2004 19041.329]
 - App version: [v0.10.2]

**Additional context**
Disks are available if typing a Disk letter manually.

**Comment by Jaiganeshkumaran** [comment] 2020-06-20 10:13
Duplicate of #488

**Closed** 2020-06-21 18:32 UTC
Labels: bug, needs-triage

**Comment by yaichenbaum** [comment] 2020-06-21 18:33
This issue has been fixed with #1168.
