### ISSUE TITLE
Add Linux distributions to sidebar if user wants

### ISSUE THREAD

**Issue by Xemanth** [files-community/files-uwp#1246] opened 2020-06-26 07:24 UTC
Hi,

It would be cool to view WSL2 Linux distributions (Network path \\wsl$\) via sidebar like they are in File Explorer.
![image](https://user-images.githubusercontent.com/6332266/85829085-7ab4d100-b792-11ea-9df2-ec0065d738c3.png)

This is the feature that came in Dev Channel (Fast Ring) Insider build 19603.
https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/
https://twitter.com/richturn_ms/status/1247947721383612421

Desktop (please complete the following information):
OS Version: Windows 10 21H1 20150.1000
App version: v0.10.2

It could be flip switch option which can be enabled by user if wanted.
"Show Linux Distributions in sidebar: yes/no"

**Comment by Jaiganeshkumaran** [comment] 2020-06-26 07:41
Duplicate of #295.

**Comment by duke7553** [comment] 2020-06-26 15:38
Duplicate of #295

**Closed by duke7553** 2020-06-26 15:38 UTC
Labels: enhancement, needs-triage
