### ISSUE TITLE
Win32 apps are launched in background

### ISSUE THREAD

**Issue by MarcAnt01** [files-community/files-uwp#1804] opened 2020-08-26 12:33 UTC
**Describe the bug**
UWP apps are open over Files UWP. For example if I open a photo with MS Photos app the new window will be in foreground, but if I open a .docx file with Word the window will be in foreground

**To Reproduce**
Open a file whose default app to open it is not UWP

**Expected behavior**
Have the same behavior of UWP apps

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: 0.13.4.0

**Additional context**
Not applicable

**Log file**
Not needed

**Comment by Jaiganeshkumaran** [comment] 2020-08-26 14:17
Duplicate of #985

**Comment by MarcAnt01** [comment] 2020-08-26 14:20
@Jaiganeshkumaran the issue talks about a specific issue with the terminal when launched in a specific scenario, while my issue aims to be general

**Comment by duke7553** [comment] 2020-08-26 17:07
Duplicate of #985 
Please follow issue 985 for updates on this one.

**Closed by duke7553** 2020-08-26 17:07 UTC
Labels: bug, needs-triage
