### ISSUE TITLE
Closing the 'property' window will also close definitively the app or its just bugged and wont open

### ISSUE THREAD

**Issue by ivanodapice** [files-community/files-uwp#659] opened 2020-04-23 19:27 UTC
![1](https://user-images.githubusercontent.com/34964967/80141009-1cf4e480-85a9-11ea-9c4d-3f7ad19130b8.PNG)
![2](https://user-images.githubusercontent.com/34964967/80141015-21210200-85a9-11ea-9a38-f2ec4eab0cbb.PNG)

**Comment by yaichenbaum** [comment] 2020-04-23 19:30
Can you add steps to reproduce this issue?

**Comment by ivanodapice** [comment] 2020-04-23 19:32
> Can you add steps to reproduce this issue?

To me it happens every time i just right click on a file/folder > click on property > close the new property window with the x red button

**Comment by yaichenbaum** [comment] 2020-04-23 19:38
@ivanodapice The app crashes when you close the properties window?

**Comment by ivanodapice** [comment] 2020-04-23 19:40
> @ivanodapice The app crashes when you close the properties window?

Yes, exactly. The app itself remain in the windows taskbar but if i click on it's icon it doesen't really shows anything.

**Comment by ivanodapice** [comment] 2020-04-23 19:45
@yair100 
![ezgif-3-e7dccd27c388](https://user-images.githubusercontent.com/34964967/80142610-c1782600-85ab-11ea-954d-e72f2ea4a9dc.gif)

**Comment by yaichenbaum** [comment] 2020-04-23 23:20
Can you check the [log file](https://github.com/duke7553/files-uwp/wiki/Opening-the-log-file) to help us debug?

**Comment by ivanodapice** [comment] 2020-04-23 23:21
@yair100 Sure, here is it
[debug.txt](https://github.com/duke7553/files-uwp/files/4525783/debug.txt)

**Comment by yaichenbaum** [comment] 2020-04-23 23:25
What version of Windows are you running?

**Comment by ivanodapice** [comment] 2020-04-23 23:26
@yair100 Windows 10 Pro Insider Preview Ver. 2004 Build 19613.1000

**Comment by yaichenbaum** [comment] 2020-04-23 23:34
I am not sure why this is happening, perhaps @duke7553 can help with this.

**Comment by lampenlampen** [comment] 2020-04-24 12:25
did you install the store version?

Had the same problem while i did work on the properties dialog, but it got away, when i merged the `develop`-branch. So i thought it was a bug, that got already fixed.

**Comment by ivanodapice** [comment] 2020-04-24 12:27
@lampenlampen Yes, the one on MS

**Comment by yaichenbaum** [comment] 2020-04-24 14:25
I was able to reproduce this once or twice but not consistently. I am guessing it's an app window bug since we are not doing anything special here. That being said, I wonder if there is anything we can do about it...

**Comment by yaichenbaum** [comment] 2020-06-18 23:32
This issue has been resolved in the latest release.

**Comment by gave92** [comment] 2020-07-27 17:54
I tested a fix for this that involves switching from AppWindow to ApplicationView... It works but seems like an overkill.

**Closed** 2020-08-06 00:19 UTC
Labels: bug, triage approved
