### ISSUE TITLE
Color labels to help highlight or categorize folders or files

### ISSUE THREAD

**Issue by Talisman39ar** [files-community/files-uwp#1592] opened 2020-07-28 00:05 UTC
**Is your feature request related to a problem? Please describe.**
In the past, MacOS had a really handy way to add color labels to files and folders to help categorize them (e.g. business vs personal) or just highlight them so they got your attention more quickly while scanning down a list. Personally I find this sufficient, and without the complexity of tags, though I know some people love tags. It also means I can more quickly find things, but without having to add them to the sidebar.

**Describe the solution you'd like**
Screenshot attached of what this could look like in list view. Designs would be needed for tile and icon views as well - if there's interest (and technical feasibility) in this idea, I can work up some.

There would be a way to assign, change and remove colors to individual or multiple items. Could be done in the ellipsis menu or with contextual menu. MacOS also allowed you to assign word labels to the colors - not sure how often this was used so maybe less important.

**Describe alternatives you've considered**
Tags - but (personally speaking), these take more time to manage, and are not as good for quickly finding a type or important item in a list as it requires more reading.

**Additional context**
A downside to this is that it may be meta data than traditional File Explorer can't make use of, unless there's a way to convert it into some searchable entity. There is a plugin of sorts for Windows called Folder Colorizer IIRC, which I have used, but it's not particularly user friendly, and it only works on folders, not files.
![image](https://user-images.githubusercontent.com/61295915/88603716-b4a01e00-d043-11ea-9ba4-eaa683daa79c.png)

**Comment by Jaiganeshkumaran** [comment] 2020-07-28 02:46
Duplicate of #1161

**Comment by Talisman39ar** [comment] 2020-07-28 15:17
Thanks! I'd done a search but hadn't turned that one up.

**Closed** 2020-07-28 20:56 UTC
Labels: enhancement, needs-triage
