### ISSUE TITLE
can not find disk H if I had not disk G

### ISSUE THREAD

**Issue by yangjieshao** [files-community/files-uwp#1031] opened 2020-06-12 12:52 UTC
My computer has C disk, D disk, E disk and H disk
Your program doesn't recognize disk H
![Snipaste_2020-06-12_20-50-33](https://user-images.githubusercontent.com/3275834/84504391-71d1f300-acee-11ea-9e80-533f16c00135.png)

![Snipaste_2020-06-12_20-51-23](https://user-images.githubusercontent.com/3275834/84504429-81e9d280-acee-11ea-9545-cbef714eca17.png)

**Comment by duke7553** [comment] 2020-06-16 23:41
Duplicate of #488

**Closed by duke7553** 2020-06-16 23:41 UTC
Labels: bug, needs-triage
