### ISSUE TITLE
Allow Resizing of the Sidebar

### ISSUE THREAD

**Issue by Lusician** [files-community/files-uwp#921] opened 2020-06-05 05:03 UTC
1.It is seems like searching button isn't displaying properly.
![image](https://user-images.githubusercontent.com/66457466/83838032-b37cff80-a72a-11ea-9a3c-436a8f7fd649.png)
2.The interface of Setting and Explorer have different style. I mean Fluent Design...Perhaps we should ensure the consistency of the design language. 
![image](https://user-images.githubusercontent.com/66457466/83838248-3b630980-a72b-11ea-88cd-bd7e66e96cf7.png)
3.You can adjust the width of left TAB so that the TAB headers are easier to read.
4.The whole interface gives me the feeling that there is no focus, especially TAB. You can enlarge the "HOME" text ,as in the case of "Drive".
Thks for your reading.

**Comment by yaichenbaum** [comment] 2020-06-05 05:06
1. Search is not yet enabled.
2. Files UWP uses fluent design which is why it looks different then File Explorer.
3. Can you give a little more detail which tabs you are talking about?
4. Do you think making the selected item in the sidebar have bold text would improve the design?

**Comment by Lusician** [comment] 2020-06-05 05:51
Thank you for checking my feedback. I'm sorry I didn't make it clear
![WIDTH](https://user-images.githubusercontent.com/66457466/83841541-a284bc00-a733-11ea-82fc-9bf14fb4dd43.png)
![home](https://user-images.githubusercontent.com/66457466/83841547-a4e71600-a733-11ea-8f83-508fca10b09f.png)
![SEETING_副本](https://user-images.githubusercontent.com/66457466/83841550-a7497000-a733-11ea-8fc3-1a24fd43707b.jpg)

**Comment by duke7553** [comment] 2020-06-11 03:40
@Lusician Thank you for reporting this. We're working on allowing users to resize the sidebar.

**Comment by duke7553** [comment] 2020-06-11 03:42
Duplicate of #672

**Closed by duke7553** 2020-06-11 03:42 UTC
Labels: enhancement, needs-triage
