### ISSUE TITLE
using single click to open file

### ISSUE THREAD

**Issue by dentistfrankchen** [files-community/files-uwp#1073] opened 2020-06-15 06:41 UTC
Hi i'm a big fun of your product! This is surely a great app, but it still should add some feature. I always use the old explorer, since i can just click on a certain file for on time(instead of double click)to open my files. This feature won't be hard to accomplish. Hope you can make this come true. Thank you in advance.

**Comment by Jaiganeshkumaran** [comment] 2020-06-15 08:22
Duplicate of #261

**Comment by dentistfrankchen** [comment] 2020-06-15 09:00
well it's good to see your update but i cannot download the newest version From store...

**Comment by dentistfrankchen** [comment] 2020-06-15 09:01
Do you need us to compile manually with v0.10?

**Comment by Jaiganeshkumaran** [comment] 2020-06-15 09:03
> Do you need us to compile manually with v0.10?

We have not implement #261 yet. I just mentioned to let you know that we're working on it.

**Comment by dentistfrankchen** [comment] 2020-06-15 23:37
ok. thanks.

**Comment by yaichenbaum** [comment] 2020-06-18 12:54
Merging with #261.

**Closed by yaichenbaum** 2020-06-18 12:54 UTC
Labels: enhancement, needs-triage
