### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by p0nkr4t** [files-community/files-uwp#37] opened 2019-02-17 11:19 UTC
Hello!
It would be great to add translations to other languages.
If you want (and if it's possible), I can help with Russian translation.
Thanks!

**Comment by SimonTek27** [comment] 2019-02-17 17:00
Hello,
i offer my help with italian language
thanks for your efforts

**Comment by duke7553** [comment] 2019-02-17 17:11
Thanks, we can definitely plan this for the initial Microsoft Store release.

**Comment by Jviix** [comment] 2019-02-19 14:10
Hey, I'd like to help with Spanish translation. So feel free to count with me :)

**Comment by duke7553** [comment] 2019-02-19 20:11
Wow, I will put it on my list to create a list of strings to be translated. I’ll keep you guys posted.

**Comment by GuusLieben** [comment] 2019-07-09 10:23
I'll help with Dutch translations once the translations list is available :)

**Comment by KaKi87** [comment] 2019-07-17 10:07
@PoorPocketsMcNewHold We'll collaborate to the french translation 😉

**Comment by Margen67** [comment] 2019-08-01 16:47
The title of the issue is misspelled: `Transaltions`

**Comment by duke7553** [comment] 2019-08-01 17:16
@Margen67 Thanks

**Comment by themoiFR** [comment] 2019-11-12 14:21
I can help setting up the Globalization and localization if needed and I can translate in french

**Comment by yaichenbaum** [comment] 2019-11-12 14:25
@themoiFR Thank you for the offer, we are definitely planning on having this done before the launch of Files UWP. I am not sure we are ready for translations at the moment since a lot of strings are going to be changing as we get the app ready for production. I would say that we will be ready for this closer to March.

**Comment by sladkOy** [comment] 2019-11-19 16:10
If anything, then I can help with the translation into Russian and Ukrainian.

**Comment by d2dyno006** [comment] 2019-12-09 18:42
I can help with the polish one

**Comment by lorisobi** [comment] 2020-01-24 18:04
I can help translating to german

**Comment by yaichenbaum** [comment] 2020-02-06 05:07
### We are going to be starting work on this much-requested option in the next few days 🚀
Adding the strings should take about a week or two and after that, we will be ready for everyone to translate to whatever languages they want.

I will let everyone know when the strings are ready and I will provide steps so you can get started. I would appreciate if everyone who is still interested can let me know. I am looking forward to everyone's contributions 😊

**Comment by KaKi87** [comment] 2020-02-06 06:09
I am still interested in translating from English to French and I am still waiting for the next release which is supposed to close so much issues and feature requests. xD

**Comment by R3voA3** [comment] 2020-02-06 09:11
I can provide help with the German translation.

**Comment by sladkOy** [comment] 2020-02-06 11:57
> ### We are going to be starting work on this much-requested option in the next few days 🚀
> Adding the strings should take about a week or two and after that, we will be ready for everyone to translate to whatever languages they want.
> 
> I will let everyone know when the strings are ready and I will provide steps so you can get started. I would appreciate if everyone who is still interested in helping out can let me know. I am looking forward to everyone's contributions 😊

I can help with translation on Ukranian and Russian

**Comment by yaichenbaum** [comment] 2020-02-07 20:10
Many strings are in the `develop` branch and ready to be localized! The ribbon control will get strings to translate later on. There are a few other areas that are missing strings and we will get to them in the near future.
I would recommend checking out these two guides to get started. If you have any questions make sure to let me know.
- https://github.com/duke7553/files-uwp/blob/develop/Translator.md
- https://github.com/duke7553/files-uwp/blob/develop/contributing.md

**Comment by KaKi87** [comment] 2020-02-07 21:15
I won't clone the entire project on my PC and load Visual Studio Code just to perform translations, sorry.
Isn't it just possible to edit the related language file directly ?

**Comment by yaichenbaum** [comment] 2020-02-07 21:17
@KaKi87 Of course! Let me know the exact French region such as fr-FR and I will upload a file.

**Comment by KaKi87** [comment] 2020-02-07 21:24
Yes, that's it

**Comment by yaichenbaum** [comment] 2020-02-07 21:27
[Files.fr-FR.xlf.zip](https://github.com/duke7553/files-uwp/files/4172988/Files.fr-FR.xlf.zip)

**Comment by Jviix** [comment] 2020-02-07 22:08
Can you upload files for es-ES? I can translate them :)

**Comment by KaKi87** [comment] 2020-02-08 08:12
@yaichenbaum I meant on the repository

**Comment by R3voA3** [comment] 2020-02-08 10:21
@yaichenbaum I have followed the instructions you've provided, but the .xlf file for the German localisation is not created. It simply fails silently. Any ideas?

**Comment by yaichenbaum** [comment] 2020-02-09 00:41
@KaKi87 @Jviix you can find the xlf files [here](https://github.com/duke7553/files-uwp/tree/develop/Files/MultilingualResources).
@R3voA3 I can add a file for German localization but I need to know the correct dialect that you want.

**Comment by KaKi87** [comment] 2020-02-09 08:22
What is `Acrylic sidebar` ?

**Comment by R3voA3** [comment] 2020-02-09 10:42
@yaichenbaum German (de-DE)

**Comment by Jviix** [comment] 2020-02-09 11:54
> @KaKi87 @Jviix you can find the xlf files [here](https://github.com/duke7553/files-uwp/tree/develop/Files/MultilingualResources).
> @R3voA3 I can add a file for German localization but I need to know the correct dialect that you want.

Pull request created. Happy to help :)

**Comment by R3voA3** [comment] 2020-02-09 13:45
https://1drv.ms/u/s!AvgETyKiA6bQkecIXPvPKphOc2A3YA?e=SHnO3O

German localisation file

**Comment by yaichenbaum** [comment] 2020-02-09 15:53
@KaKi87 Unfortunately even if `text` and `Content` sometimes get the same translation you still need to have it translated. In this case, one is for an item in the navigation view and one is for a header on the page.

![image](https://user-images.githubusercontent.com/39923744/74105217-e242ea80-4b29-11ea-95a9-b3f8780a1670.png)

> What is Acrylic sidebar (SettingsAppearanceAcrylicSidebar.Text) ?

Acrylic Sidebar is the option to turn on acrylic on the left navigation menu

![image](https://user-images.githubusercontent.com/39923744/74105279-5e3d3280-4b2a-11ea-95f2-75189d05767b.png)

> There's a typo on english source SettingsPreferencesMusicLocation.PlaceholderText : Set custom mcusic location

Thank you for reporting this typo!

> OneDrive (SettingsPreferencesOneDrive.Text) isn't supposed to be translated.

I can remove that string, for now you can just ignore it.

> Does Terminal Applications (SettingsPreferencesTerminalApplications.Text) mean CLI ?

Terminal Applications will let you choose the default CLI to open from Files.

![image](https://user-images.githubusercontent.com/39923744/74105255-2f26c100-4b2a-11ea-9314-4c79259d610b.png)

**Comment by KaKi87** [comment] 2020-02-09 16:02
> Unfortunately even if `text` and `Content` sometimes get the same translation you still need to have it translated. In this case, one is for an item in the navigation view and one is for a header on the page.

What's the technical problem here ?

> Acrylic Sidebar is the option to turn on acrylic on the left navigation menu

What does the `acrylic` term mean exactly ?

**Comment by yaichenbaum** [comment] 2020-02-09 16:06
The problem is that different controls have different properties for displaying text, sometimes is content, sometimes its text and sometimes it can be something like tooltip. The main issue is that each string is hooked up to different properties so we need a string for each property.

Acrylic is the blur effect in Windows 10

![image](https://user-images.githubusercontent.com/39923744/74105453-e4a64400-4b2b-11ea-8bad-8b6cce7bc0d8.png)

**Comment by R3voA3** [comment] 2020-02-12 09:17
@yaichenbaum Can you pin this issue? Also, did you see my translation file?

> https://1drv.ms/u/s!AvgETyKiA6bQkecIXPvPKphOc2A3YA?e=SHnO3O

**Comment by yaichenbaum** [comment] 2020-02-12 14:38
@R3voA3 I did, thank you so much!

**Comment by GuusLieben** [comment] 2020-02-13 18:20
Submitted a PR (#411) which contains the Dutch translations

**Comment by yaichenbaum** [comment] 2020-03-08 20:02
I started adding strings for the ribbon in the `develop` branch, feel free to get to it on your own schedule.

**Comment by duke7553** [comment] 2020-03-09 21:59
I'll remove the milestone to reflect this being an ongoing effort

**Comment by yaichenbaum** [comment] 2020-03-20 02:57
I started adding strings for the sidebar. Make sure to update all your translations so you can get the best experience when we roll out the next update 🙂

**Comment by yaichenbaum** [comment] 2020-03-25 22:21
I added the strings for the brand new Extract Files dialog. The actual feature is still a work in progress but it's working really nicely so far!

**Comment by sladkOy** [comment] 2020-03-26 16:30
I am very sorry, I can not help with the translation of the application. Use Google translator to translate into my languages

**Comment by yaichenbaum** [comment] 2020-03-26 16:34
@sladkOy Unfortunately that won't work since many strings depend on the context of where it is being used and require's a human to translate accordingly.

**Comment by yaichenbaum** [comment] 2020-04-03 16:15
The v0.7.3 release is almost ready, there are multiple new strings that need to be translated. The majority of the basic application now has strings. I am aware that some dialog's are still missing strings, if you notice something that is missing strings, please mention it in this issue.

**Comment by R3voA3** [comment] 2020-04-03 16:22
Are you sure my last translations were merged into the developement branch? I think I am translating some of them for the second time now. @yaichenbaum

**Comment by yaichenbaum** [comment] 2020-04-03 17:59
It was caused by the replacement of the ribbon control.

**Comment by xPoppyx** [comment] 2020-04-07 12:36
I have put in "pull requests" the Spanish translation

**Comment by BuraChuhadar** [comment] 2020-04-08 03:09
I am sending translations for Turkish: https://github.com/duke7553/files-uwp/pull/541

**Comment by BuraChuhadar** [comment] 2020-04-08 03:12
#541

**Comment by yaichenbaum** [comment] 2020-04-12 20:42
Multiple new strings have been added to the `develop` branch.

**Comment by SimoneRaspagni** [comment] 2020-04-15 13:32
Hi! I am sending translations for Italian.
[Files it-IT.zip](https://github.com/duke7553/files-uwp/files/4481463/Files.it-IT.zip)

**Comment by KaKi87** [comment] 2020-04-15 13:47
Should `<target>`'s `state` attribute be changed from `new` to `translated` when translating ?
If yes, are there other possible values ?
Thanks

**Comment by SimoneRaspagni** [comment] 2020-04-15 14:23
> Should `<target>`'s `state` attribute be changed from `new` to `translated` when translating ?
> If yes, are there other possible values ?
> Thanks


Hi,
thank you I corrected: now I set all translated strings with "final" tag .
[Files it-IT.zip](https://github.com/duke7553/files-uwp/files/4481731/Files.it-IT.zip)

**Comment by yaichenbaum** [comment] 2020-04-17 17:51
@SimoneRaspagni Thank you.

**Comment by xPoppyx** [comment] 2020-04-22 18:55
strings need to be added for this:
![80010185-0b6fe780-8498-11ea-851a-b0aa5bd2b4f7](https://user-images.githubusercontent.com/61259627/80021916-44648800-84a9-11ea-8c77-6ea5b46c9090.png)

**Comment by xPoppyx** [comment] 2020-04-22 19:41
Date modified: "X seconds ago", "X minutes ago", etc. , still displayed only in English
![Anotación 2020-04-22 144546](https://user-images.githubusercontent.com/61259627/80026185-b8a22a00-84af-11ea-84f5-e06bb702800d.png)
![Anotación 2020-04-22 154009](https://user-images.githubusercontent.com/61259627/80026188-ba6bed80-84af-11ea-89c2-c271b8afbdf3.png)

**Comment by Senko-Dev** [comment] 2020-05-19 19:01
Can I help translate for Arabic langauage?

**Comment by yaichenbaum** [comment] 2020-05-19 20:16
@Senko-Dev Absolutely! Let us know if you have any questions.

**Comment by Senko-Dev** [comment] 2020-05-20 22:05
What does this mean @yaichenbaum 
![image](https://user-images.githubusercontent.com/32780515/82502122-1fdaea80-9aff-11ea-9e4e-957c58230fd8.png)

**Comment by Senko-Dev** [comment] 2020-05-20 22:17
I also can't translate because I don't see the option. @yaichenbaum

**Comment by Senko-Dev** [comment] 2020-05-20 22:18
Oh, I didn't restart VS, no worries

**Comment by yaichenbaum** [comment] 2020-05-20 22:22
@Senko-Dev Make sure to check out the documentation on translating Files and what tools you need to do that.

**Comment by Senko-Dev** [comment] 2020-05-20 22:25
@yaichenbaum What am I supposed to do with the XLF file?

**Comment by yaichenbaum** [comment] 2020-05-26 18:52
I want to give a big thanks to everyone who has worked on translations, we are getting close to launching the first official preview #676 and I wanted to mention a couple things to keep in mind.
- **Missing strings**, we have been adding strings for different parts of the app as we work on refining the app. Even with all the strings we added, we have definitely missed some, so make sure to let us know if you find an area of the app that is missing strings.
- **Out of date translations**, the app has seen a lot of improvements over the past few months and while the app has already been localized for many languages, a lot of those translations are out of date. If you notice a language that is out of date and you know the language, feel free to open a pull request that updates the translations.
- **Adding translations**, Files UWP welcomes contributions, localizing Files UWP is easy and we put together a guide to help you do it over here https://github.com/files-community/files-uwp/blob/master/Translator.md.

**Comment by R3voA3** [comment] 2020-05-26 19:43
@yaichenbaum Which branch contains the latest translation files? Translations branch seems to be gone.

**Comment by yaichenbaum** [comment] 2020-05-26 19:46
@R3voA3 The `master` branch contains the latest code, the documentation is a little out of date right now.

**Comment by yaichenbaum** [comment] 2020-06-03 04:16
I want to thank everyone who has participated in translating Files UWP, being that most of the app is now localized, I am going to be closing this pull request. If there are any issues with localization, feel free to open an issue or just continue using this issue even in it's closed state.

**Closed by yaichenbaum** 2020-06-03 04:16 UTC
Labels: enhancement, help wanted
