### ISSUE TITLE
Random app crashes related to changing layout type.

### ISSUE THREAD

**Issue by AqilCont** [files-community/files-uwp#1021] opened 2020-06-11 23:51 UTC
## Describe the bug
First time trying grid view(medium), and the app completely hangs over and eventually crashes. Subsequent crashes follow after opening the app later, in random locations.

### To Reproduce(Not completely sure, but this is what I found)
1. Go to a place with a lot of items in it.
2. Try to change a layout mode at all.

### Expected behavior
I expected it to work.

## Screenshots
![2020-06-11 19-31-37](https://user-images.githubusercontent.com/32044067/84449908-ba20e080-ac1c-11ea-9506-74a84a738ced.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - App version: v0.10.1.0

**Comment by Jaiganeshkumaran** [comment] 2020-06-12 01:27
Duplicate of #857

**Comment by yaichenbaum** [comment] 2020-06-12 01:47
@AqilCont Thank you for opening this issue, I am merging this issue with #857.

**Closed by yaichenbaum** 2020-06-12 01:47 UTC
Labels: bug, needs-triage
