### ISSUE TITLE
App opening behind the main app.

### ISSUE THREAD

**Issue by jrwut** [files-community/files-uwp#1270] opened 2020-06-27 19:13 UTC
**Describe the bug**
A clear and concise description of what the bug is when I open files or even I want to submit feedback in about section, the app like Photo and Edge is opening in the background, not show up in front. I am not sure this is the bug of windows or not that will always show the current app on top.

**To Reproduce**
1. Go to 'folder or about in setting'
2. Click on 'photos or submit feedback'
3. Then 'the apps are opening in the background'
4. This is not an error, but it should appear in the front.

**Expected behavior**
A clear and concise description of what you expected to happen. It should appear on top of the current uwp app.

**Screenshots**
![image](https://user-images.githubusercontent.com/67519322/85930186-e6ab4c80-b8ec-11ea-9ef1-2dc23d2f6d69.png)
![image](https://user-images.githubusercontent.com/67519322/85930191-fcb90d00-b8ec-11ea-9ef2-4954c929092a.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 20H2]
![image](https://user-images.githubusercontent.com/67519322/85930221-338f2300-b8ed-11ea-826c-c355b5105e5a.png)

 - App version: [v0.10.2.0]

**Additional context**
it happens to other UWP app too for example Twitter app, when I open the link from the Twitter app, the new Edge will open in the background.

**Comment by Jaiganeshkumaran** [comment] 2020-06-28 02:36
It's a Windows bug and not Files UWP bug since it also affects other applications.

**Comment by duke7553** [comment] 2020-07-04 16:56
Duplicate of #985

**Closed by duke7553** 2020-07-04 16:56 UTC
Labels: bug, needs-triage
