### ISSUE TITLE
Issue with Accessing Network Drives

### ISSUE THREAD

**Issue by vhellberg** [files-community/files-uwp#1318] opened 2020-07-01 10:51 UTC
I am not sure if this is a bug or whether the feature is just not supported yet?   Does Files-UWP support network drives?  When I select one of my network drives the feedback is that the folder is empty, which is not the case.

**To Reproduce**
1. Open Files-UWP
2. Click on one of the network drives.  In my case the p: drive that points to a file server on our network.
3. See error - the feedback is that the folder is empty.  Even clicking on the Refresh icon doesn't help.

**Expected behavior**
I would exp[ect a list of folders available on the P: drive.

**Screenshots**
Screenshot of the app showing the p: selected and no folders or contents shown for that drive.
![image](https://user-images.githubusercontent.com/67633515/86235640-08306080-bb99-11ea-83ad-e54b97016a2f.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 10.0.18362 Build 18362]
 - App version: [v0.11.0.0]

**Additional context**
This is my first attempt at using your new application.   I hope that this issue can be resolved as I use my network drives a lot for file handling.

**Comment by Jaiganeshkumaran** [comment] 2020-07-01 11:12
Duplicate of #642

**Comment by vhellberg** [comment] 2020-07-01 12:48
> Duplicate of #642

yes apologies, I did not check existing bugs before reporting this.  This is indeed a Duplicate.  I'm not sure how to link this bug to #642 ?

**Comment by Jaiganeshkumaran** [comment] 2020-07-01 12:57
@vhellberg You can't really link two issues. Since your problem is with the Store version rather than the GitHub version, you report your issue at #642 and close this one.

**Closed** 2020-07-01 13:18 UTC
Labels: bug, needs-triage
