### ISSUE TITLE
crashes when changing the layout mode.

### ISSUE THREAD

**Issue by kleuton05** [files-community/files-uwp#1266] opened 2020-06-27 13:57 UTC
the layout modes GRID VIEW (LARGE) and LIST VIEW work, however when selecting the GRID VIEW (MEDIUM), GRID VIEW (SMALL) and TILES VIEW modes, the app crashes.
this occurs when using my external hd.
this is an annoying bug that hasn't been fixed in a long time.

**Comment by duke7553** [comment] 2020-06-27 14:52
@kleuton05 Thank you for reporting this bug. What app version are you on?

**Comment by kleuton05** [comment] 2020-06-27 15:30
> @ kleuton05 Obrigado por relatar este bug. Em qual versão do aplicativo você está?

v 0.11

**Comment by duke7553** [comment] 2020-08-28 15:54
@kleuton05 I can't reproduce this one anymore. Please let me know if this was fixed, as otherwise I'll be closing this soon.

**Comment by duke7553** [comment] 2020-08-29 21:50
Please re-open if this becomes an issue again. Thanks!

**Closed by duke7553** 2020-08-29 21:50 UTC
Labels: bug, triage approved
