### ISSUE TITLE
Add context menu entries to the tabs

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1669] opened 2020-08-06 15:41 UTC
- Close all other tabs
- Close tabs to the right
- Duplicate tab
- Close tab

Similar to the Edge browser.

![image](https://user-images.githubusercontent.com/17484252/89552134-0b5be380-d80c-11ea-8e4a-88b89b1c9714.png)

**Comment by Jaiganeshkumaran** [comment] 2020-08-06 15:43
Duplicate of #260

**Closed** 2020-08-06 16:04 UTC
Labels: feature_request, needs-triage
