### ISSUE TITLE
The app crashes when dragging an item on it from winrar

### ISSUE THREAD

**Issue by XPoppyX** [files-community/files-uwp#798] opened 2020-05-18 02:03 UTC
![crash](https://user-images.githubusercontent.com/61259627/82167399-af776380-9889-11ea-8c69-4c6e7f9c082b.gif)
v0.8.0

**Comment by Jaiganeshkumaran** [comment] 2020-06-09 05:03
Duplicate of #834

**Comment by yaichenbaum** [comment] 2020-07-07 04:16
Merging with #829.

**Closed by yaichenbaum** 2020-07-07 04:16 UTC
Labels: bug, needs-triage
