### ISSUE TITLE
Rename will open the file / folder

### ISSUE THREAD

**Issue by ChelaruCatalin** [files-community/files-uwp#825] opened 2020-05-21 21:09 UTC
Version 0.8.2.0 from window store.

When rename is selected from the contextual menu the file is open or the folder is open.

**Comment by xPoppyx** [comment] 2020-05-21 21:15
#651

**Comment by duke7553** [comment] 2020-06-18 09:39
Duplicate of #651 

_Please Note: flags for experimental functionality should not be considered supported_

**Closed by duke7553** 2020-06-18 09:39 UTC
Labels: bug, needs-triage
