### ISSUE TITLE
Not bad but just a little thing

### ISSUE THREAD

**Issue by awsomenes** [files-community/files-uwp#1554] opened 2020-07-23 17:44 UTC
**Is your feature request related to a problem? Please describe.**
no not really
**Describe the solution you'd like**
When you right click on a directory and choose open in windows terminal it opens the terminal but not in front of the file explorer, it appears in the taskbar and then you have to click on it from there. I would like if the windows terminal just popped up like the regular command prompt does
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment] 2020-07-23 17:46
Duplicate of #985.

**Closed** 2020-07-23 17:45 UTC
Labels: bug, enhancement, needs-triage
