### ISSUE TITLE
"This PC" view - all disk (and network drives)  sizes and free space in one view

### ISSUE THREAD

**Issue by andyfmidd** [files-community/files-uwp#966] opened 2020-06-09 21:43 UTC
**Is your feature request related to a problem? Please describe.**
No overview of all disks and sizes/freespace.

**Describe the solution you'd like**
Like the native PC explorer, ability to see all disks, network drives etc in one view

**Describe alternatives you've considered**
Free space etc is available as a tooltip for individual drives.

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Jaiganeshkumaran** [comment] 2020-06-10 06:20
Duplicate of #210.

**Comment by duke7553** [comment] 2020-06-11 03:37
We'd love to hear what you think about future work on a This PC section. To add your own take on it, and stay up to date, please subscribe to issue #210 .

**Closed by duke7553** 2020-06-11 03:37 UTC
Labels: enhancement, widget
