### ISSUE TITLE
Make tabs more intuitive

### ISSUE THREAD

**Issue by RandomAJL** [files-community/files-uwp#1453] opened 2020-07-14 15:58 UTC
I believe that doing the following would help make this application feel more intuitive:

- Dragging a tab out of the window opens that tab in a new window
- Dragging a tab when that is the only tab in the window moves the window instead of the tab

I think it'd be great if dragging a tab out of the window will open that tab in it's own window as users will likely do this instinctively anyways (as this is how tabs work in browsers like Chrome, Edge & Firefox).

By having it so when the user drags the tab out of the window, letting go of the tab will open that tab in a new window at the point where the user let go of the tab. There should only be one exception to this feature being that dragging a tab when it's the only tab in the window (in this case dragging the single tab) should revert to moving the window around.

For reference, open a browser like **Edge, Firefox or Chrome** and **drag a tab out of the window** when there are **multiple tabs present** and when there is only **one tab present**; that is the experience I believe that would help make this application feel **more intuitive for the end-user**.

**Comment by XPoppyX** [comment] 2020-07-14 16:15
Drag and drop for tabs has already been implemented, and will be available in the next version of the app: #1432

**Comment by RandomAJL** [comment] 2020-07-14 17:18
https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.tabview.tabdroppedoutside?view=winui-2.4

**Comment by duke7553** [comment] 2020-07-14 18:16
Thank you for creating this feedback item. A solution to this issue is currently resolved in one of our active development branches and will be shipped after we've validated that everything works properly via code review. 

We will notify you when this feature is in a PR

**Comment by duke7553** [comment] 2020-07-14 18:19
Duplicate of #828 

Please subscribe to the original feedback item for the latest notifications and status updates.

**Closed by duke7553** 2020-07-14 18:19 UTC
Labels: enhancement, feature_request, needs-triage
