### ISSUE TITLE
打开文件内容较多的文件夹会崩溃 闪退

### ISSUE THREAD

**Issue by adminil** [files-community/files-uwp#1274] opened 2020-06-28 02:12 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by Jaiganeshkumaran** [comment] 2020-06-28 02:34
Duplicate of #799

**Comment by yaichenbaum** [comment] 2020-06-28 02:37
Merging with #799.

**Closed by yaichenbaum** 2020-06-28 02:37 UTC
Labels: bug, needs-triage
