### ISSUE TITLE
Only a single OneDrive account is shown on the left sidebar when I have 2 accounts both integrated to the file manager.

### ISSUE THREAD

**Issue by jiyuge** [files-community/files-uwp#995] opened 2020-06-11 01:26 UTC
**Is your feature request related to a problem? Please describe.**
I have 2 OneDrive accounts, one personal and one school. On the left sidebar, there is only the horizontal tab for my school account, which is added after my personal account that I set up my computer with.

**Describe the solution you'd like**
Please show tabs or all OneDrive accounts on the side bar.

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by duke7553** [comment] 2020-06-11 03:34
Duplicate of #16

**Closed by duke7553** 2020-06-11 03:34 UTC
Labels: enhancement, needs-triage
