### ISSUE TITLE
Switch to New Window when it opens

### ISSUE THREAD

**Issue by sumanth-vs** [files-community/files-uwp#1165] opened 2020-06-20 13:38 UTC
When an App, or File is opened, Files UWP remains in focus, and doesn't switch to the new App/File

**Comment by Jaiganeshkumaran** [comment] 2020-06-20 14:15
Duplicate of #985

**Comment by yaichenbaum** [comment] 2020-06-21 02:51
Merging with #985?

**Closed by yaichenbaum** 2020-06-21 02:51 UTC
Labels: bug, needs-triage
