### ISSUE TITLE
Shortcuts not shown

### ISSUE THREAD

**Issue by andyfmidd** [files-community/files-uwp#968] opened 2020-06-09 21:54 UTC
**Describe the bug**
No shortcuts displayed

**To Reproduce**
1. Go to Home
2. Click on Desktop

**Expected behavior**
All files and Shortcuts. Only files are shown

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 insider build 19640 release 200530-1731]
 - App version: [v0.9.2]

**Comment by XPoppyX** [comment] 2020-06-09 22:19
#112

**Comment by yaichenbaum** [comment] 2020-06-10 02:00
Shortcuts are not yet supported.

**Comment by duke7553** [comment] 2020-06-11 03:46
Duplicate of #177 

(Moving this into a single issue)

**Closed by duke7553** 2020-06-11 03:46 UTC
Labels: bug
