### ISSUE TITLE
Opening new tab causes the app to crash

### ISSUE THREAD

**Issue by SOI7** [files-community/files-uwp#1708] opened 2020-08-12 12:13 UTC
This is the debug log:

2020-08-12 14:11:39.9499|INFO|Files.App|App launched|
2020-08-12 14:11:40.1061|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed|
2020-08-12 14:11:40.1529|INFO|Files.Filesystem.DrivesManager|Drive added: D:\, CDRom|
2020-08-12 14:11:40.1842|INFO|Files.Filesystem.DrivesManager|Drive added: E:\, Fixed|
2020-08-12 14:11:45.2557|ERROR|Files.App|Puntatore non valido.

Object reference not set to an instance of an object.|System.NullReferenceException: Puntatore non valido.

Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Void*, Void*) + 0x48
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler__Impl.Invoke(__ComObject, Object, NotifyCollectionChangedEventArgs) + 0xb0
   at System.Action`2.InvokeClosedStaticThunk(T1, T2) + 0x2e
   at System.Action`2.InvokeMulticastThunk(T1, T2) + 0x4e
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs) + 0x2b
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction, Object, Int32) + 0x47
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32, T) + 0x6c
   at Files.Views.MainPage.<AddNewTab>d__10.MoveNext() + 0xb66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at Files.Interacts.Interaction.<>c__DisplayClass11_0.<<OpenDirectoryInNewTab_Click>b__0>d.MoveNext() + 0xcf
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_11[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__23[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0x12a3470

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: v0.13.0

**Comment by XPoppyX** [comment] 2020-08-12 12:55
If it happens after disabling the multitasking flyout, then it is a duplicate of #1641

**Comment by SOI7** [comment] 2020-08-12 12:57
> If it happens after disabling the multitasking flyout, then it is a duplicate of #1641

Oddly enough, multitasking was disabled by default after updating the app. Now I've disabled it and tabs work again

**Closed** 2020-08-12 12:58 UTC
Labels: bug, needs-triage
