### ISSUE TITLE
Cannot view contents of a mapped network drive

### ISSUE THREAD

**Issue by eighteentee** [files-community/files-uwp#1272] opened 2020-06-27 20:38 UTC
**Describe the bug**
Cannot see the contents of a mapped network drive. App just says 'This folder is empty'. It is viewable using regular Windows Explorer.

**To Reproduce**
1. Simply cannot see the contents of a mapped network drive

**Expected behavior**
I expected to be able to browse my mapped network drive just as I do through Windows Explorer

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - App version: 0.10.2.0

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by XPoppyX** [comment] 2020-06-27 21:15
Duplicate of #642

**Comment by yaichenbaum** [comment] 2020-06-28 02:37
Merging with #642.

**Closed by yaichenbaum** 2020-06-28 02:37 UTC
Labels: bug, needs-triage
