### ISSUE TITLE
Crash when multitasking flyout is disabled

### ISSUE THREAD

**Issue by Dylan-Osborne** [files-community/files-uwp#1798] opened 2020-08-25 07:01 UTC
**Describe the bug**
Files UWP crashes when attempting to open any folder or path when "Show multitasking flyout in the navigation toolbar" is disabled.

**To Reproduce**
1. Upgrade to the latest version (0.13.4.0)
2. Go to Settings ->Experimental and disable "Show multitasking flyout in the navigation toolbar"
3. Go back to the home page and try open any folder or type something in the path box
4. Files UWP crashes

**Expected behavior**
Files UWP should browse to that path without crashing.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 19041.450]
 - App version: [v0.13.4.0]

**Additional context**
Enabling "Show multitasking flyout in the navigation toolbar" under Settings ->Experimental stops this crash from happening

**Log file**
[debug.txt](https://github.com/files-community/files-uwp/files/5121851/debug.txt)

**Comment by generalguy41** [comment] 2020-08-25 12:34
Duplicate of #1641

**Comment by Dylan-Osborne** [comment] 2020-08-25 13:24
@generalguy41 This isn't to do with creating tabs. This crash occurs when trying to browse away from the home page.

**Comment by generalguy41** [comment] 2020-08-25 13:26
Fair. I wonder if both would be fixed by addressing the issue.

**Comment by yaichenbaum** [comment] 2020-08-25 23:20
Merging with #1641.

**Closed by yaichenbaum** 2020-08-25 23:20 UTC
Labels: bug, needs-triage
