### ISSUE TITLE
Can't drag and drop file into Files UWP

### ISSUE THREAD

**Issue by xumepoc** [files-community/files-uwp#834] opened 2020-05-25 07:33 UTC
**Describe the bug**
You can drag and drop a file from Files UWP to anywhere else. But It seems that it is not possible to do the opposite: to drag and drop a file in Files UWP. For example if you want to drag and drop a file into a opened tab in Files UWP it is not possible

**To Reproduce**
Just try to drag and drop a file from a outlook application or even the File Explorer into the Files UWP.

**Expected behavior**
The drag and drop should be supported when done into the Files UWP

**Screenshots**
![Annotation 2020-05-25 102940](https://user-images.githubusercontent.com/46034979/82789297-b9452c00-9e72-11ea-9ac2-6ad1b6463e61.jpg)

**Desktop (please complete the following information):**
 - OS Version: 10 1909 18363657
 - App version: v0.8.2.0

**Comment by duke7553** [comment] 2020-06-18 09:55
Duplicate of #829

**Comment by duke7553** [comment] 2020-06-18 09:56
I moved this into #829 since they're similar. Please follow that issue and the releases page to keep track of the solution 🙂

**Closed by duke7553** 2020-06-18 09:55 UTC
Labels: bug, needs-triage
