### ISSUE TITLE
Move files and folders

### ISSUE THREAD

**Issue by JavaAppleJr** [files-community/files-uwp#1520] opened 2020-07-20 16:30 UTC
I can't seem to find a way to move files and folders. Is that even a function?

**Comment by Jaiganeshkumaran** [comment] 2020-07-21 01:32
You can cut a file or folder and paste it somewhere else.

**Comment by hunterlan** [comment] 2020-08-02 08:33
> You can cut a file or folder and paste it somewhere else.

It's the crutch. I don't want open another "Files UWP" for moving file/folder from one place to another place. Default file explorer has function "Move/Copy to...", which calling dialog window, where you choose the destination. It would be better, if developer team added this feature.

**Comment by XPoppyX** [comment] 2020-08-04 20:18
If he is referring to the "Move to" function then it is a duplicate of #946 
@yaichenbaum

**Closed** 2020-08-06 00:47 UTC
Labels: feature_request, needs-triage
