### ISSUE TITLE
Option to open file/folder with a single click instead of double click

### ISSUE THREAD

**Issue by Sav22999** [files-community/files-uwp#1849] opened 2020-08-31 19:22 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by Dylan-Osborne** [comment] 2020-09-01 05:25
Possible duplicate of #261

**Closed** 2020-09-01 12:20 UTC
Labels: duplicate
