### ISSUE TITLE
View settings saves individial for each folder

### ISSUE THREAD

**Issue by lionnesquaer** [files-community/files-uwp#1183] opened 2020-06-21 14:40 UTC
It would be great if you make that view setting saves individal for each folder. ("Standart Size Icons" for Pictures,  "Table" for Documents and Downloads for example) Like it work in vanilla Windows Explorer.
Thank you!

**Comment by XPoppyX** [comment] 2020-06-22 14:37
Duplicate of #530

**Comment by yaichenbaum** [comment] 2020-06-28 02:39
Merging with #530.

**Closed by yaichenbaum** 2020-06-28 02:39 UTC
Labels: enhancement, needs-triage
