### ISSUE TITLE
File Type in Grid View should have different font

### ISSUE THREAD

**Issue by R3voA3** [files-community/files-uwp#1585] opened 2020-07-27 08:07 UTC
![image](https://user-images.githubusercontent.com/17484252/88518277-77f70700-cff0-11ea-961c-2b324a30b525.png)

The file type and the folder name have the same font size, type and color and it's hard to distinguish them from one another at first glance.
I'd suggest to maybe use a light grey for the item type and size.

**Comment by R3voA3** [comment] 2020-07-27 08:07
![image](https://user-images.githubusercontent.com/17484252/88518578-fe134d80-cff0-11ea-9632-cfba861b1dca.png)

**Comment by Jaiganeshkumaran** [comment] 2020-07-27 08:56
We can have opacity as 6 for those other details.

**Comment by SOI7** [comment] 2020-07-27 10:12
Alternatively, instead of making it use a different font, they could use the same font, but the system accent color

![Annotazione 2020-07-27 121025](https://user-images.githubusercontent.com/50930970/88531003-7afaf300-d002-11ea-9fc4-015e410f701e.png)

**Comment by R3voA3** [comment] 2020-07-27 10:24
That looks very nice as well. Maybe as an option in Appearance?

**Comment by SOI7** [comment] 2020-07-27 10:25
Up to the devs, although I think the app in general could use more color here and there

**Comment by XPoppyX** [comment] 2020-07-27 11:21
> Alternatively, instead of making it use a different font, they could use the same font, but the system accent color
> 
> ![Annotazione 2020-07-27 121025](https://user-images.githubusercontent.com/50930970/88531003-7afaf300-d002-11ea-9fc4-015e410f701e.png)

Other users will like that there is a little more color, because I have read many complaints that the app is very monochromatic

**Comment by R3voA3** [comment] 2020-07-27 12:20
I think it should be coloured as well but with the option to change the color in the appearance settings.

**Comment by Talisman39ar** [comment] 2020-07-27 13:30
Could run into contrast issues if default color is subtle against white are dark background, so would need a way to handle that (or just pick a color each for light and dark mode and go with that). File Explorer does the sub-details in gray vs black for the file/folder name, which I like even though it's monochrome. Adding a color to the secondary information could giveit more visual prominence than the name, which is what you're mostly going to want to focus on.

**Comment by mdtauk** [comment] 2020-07-27 13:38
Using the Accent colour makes it appear as if it would be a link or button

But dimming the text to make the folder/file name stand out, is a sensible idea

**Comment by XPoppyX** [comment] 2020-07-27 14:03
![Anotación 2020-07-27 100338](https://user-images.githubusercontent.com/61259627/88551111-77f70700-cff0-11ea-844c-518967b41abd.png)

**Comment by R3voA3** [comment] 2020-07-27 14:22
Looks very good and it adds a neat accent.

**Comment by XPoppyX** [comment] 2020-07-27 14:29
different color tone will need to be used depending on whether it is in dark or light mode, the color tone that I used in that screenshot for example looks good in light mode, but not so much in dark mode

**Comment by SOI7** [comment] 2020-07-27 14:31
Tbf this is a problem with Windows 10 as a whole

**Comment by mdtauk** [comment] 2020-07-27 18:10
Take the text foreground colour, and set the alpha to 60%

**Comment by XPoppyX** [comment] 2020-07-27 19:25
**Color:** SystemAccentColorLight1

![light1](https://user-images.githubusercontent.com/61259627/88582298-7c391980-d01c-11ea-9a30-947a64dc8426.png)
![light2](https://user-images.githubusercontent.com/61259627/88582301-7d6a4680-d01c-11ea-8475-5969287a03ac.png)

-----------------------------------

**Color:** SystemAccentColor
**Opacity:** 60%

![normal2](https://user-images.githubusercontent.com/61259627/88582586-f6699e00-d01c-11ea-944a-4608751a134b.png)
![normal1](https://user-images.githubusercontent.com/61259627/88582582-f49fda80-d01c-11ea-9a5e-2ba371e2299e.png)

-------------------------------------

**Color:** SystemAccentColor

![accent1](https://user-images.githubusercontent.com/61259627/88582855-5bbd8f00-d01d-11ea-80e6-959d36c20f90.png)
![accent2](https://user-images.githubusercontent.com/61259627/88582865-5e1fe900-d01d-11ea-86d3-e2699d53c4ad.png)

**Comment by SOI7** [comment] 2020-07-27 19:30
SystemAccentColor seems the best to me, unless there's a way to make the tint theme-aware. In that case I'd use SystemAccentColorLight1 for Dark Mode and 60% opacity for Light Mode

**Comment by mdtauk** [comment] 2020-07-27 19:39
> SystemAccentColor seems the best to me, unless there's a way to make the tint theme-aware. In that case I'd use SystemAccentColorLight1 for Dark Mode and 60% opacity for Light Mode

You use a ThemeDictionary and set the colour of the brush resource for Light, Dark, and High Contrast themes.  The correct value is applied when the system theme changes.

I still think using the Accent colour is a mistake, as it implies there is an action or importance to what is essentially an inactive caption for the folder and file items.

**Comment by Talisman39ar** [comment] 2020-07-27 19:49
> I still think using the Accent colour is a mistake, as it implies there is an action or importance to what is essentially an inactive caption for the folder and file items.

I agree with this as good UX practice. Adding a color to the less important item makes it more visually prominent, which is going to make it harder to scan the list quickly, not easier. (Unless you do something else to rebalance the visual hierarchy, such as making the primary item larger, bold, etc. But that seems overkill). Since the original request here was about making the tiles easier to scan by adjusting the visual hierarchy, to me it's a step backward to add prominence to the secondary elements.

**Comment by XPoppyX** [comment] 2020-07-27 19:56
![Anotación 2020-07-27 155601](https://user-images.githubusercontent.com/61259627/88585950-c4a70600-d021-11ea-9986-4cf91c37b87e.png)
![Anotación 2020-07-27 155615](https://user-images.githubusercontent.com/61259627/88585954-c53f9c80-d021-11ea-9c96-de6bfb8a6c3c.png)

**Comment by mdtauk** [comment] 2020-07-27 19:59
Perfect @XPoppyX

**Comment by SOI7** [comment] 2020-07-27 20:00
Gotta agree with mdatuk on second thought, and that seems the most practical and logical approach. I'm pretty sure we can find other areas to use more color in the future

**Comment by mdtauk** [comment] 2020-07-27 20:02
> Gotta agree with mdatuk on second thought, and that seems the most practical and logical approach. I'm pretty sure we can find other areas to use more color in the future

If you have performed a search, the letters searched for could be displayed in the Accent Colour.  Also for the Details view, the currently selected header, the text in that column should probably be in the Foreground colour, and everything else being in the faded colour.

**Comment by XPoppyX** [comment] 2020-07-27 20:49
the problem is in details view, when selecting an item, **gray** does not look good depending on the accent color
![83441748-08f89a00-a415-11ea-83c5-ec2cc29b05ce](https://user-images.githubusercontent.com/61259627/88588598-cffc3080-d025-11ea-8df9-fc1ef10afe57.png)

as I had said in #1170, 
for **dark mode:** white 60% opacity
for **light mode:** black 60% opacity

**Comment by SOI7** [comment] 2020-07-27 20:51
I thought you could bypass this issue by altering the opacity instead of the tint

**Comment by XPoppyX** [comment] 2020-07-27 23:31
the app crashes when I use "ThemeResource" in foreground (DataGridTextColumn)

**Comment by XPoppyX** [comment] 2020-08-02 17:13
could merge with #1170  and close this

**Closed** 2020-09-06 03:26 UTC
Labels: Implemented, enhancement
