### ISSUE TITLE
Cannot see aliases and volumes

### ISSUE THREAD

**Issue by psdcovers** [files-community/files-uwp#855] opened 2020-05-26 19:15 UTC
**Describe the bug**
Firstly --- HOLY WOW!  As a macOS user who switched to Linux and is using vmware for Win10 all I can say is Files UWP brings sanity to the file manager.  I look forward to buying it.

THE BUG:  I'm currently working in Windows 10 Pro (paid) using VMWare Pro (paid) and to avoid filling up the VM with work that only exists in the VM I'm working from my mounted Synology NAS drive.  More specifically, I'm mounting the drive as well as using Synology's Drive app (it effectively replaces DropBox, works the same way).

SUMMARY: I'm working on files from a NAS whose folders are on my Desktop as aliases.

**To Reproduce**
[1] with uwp open I navigate to the Desktop view in the left sidebar
[2] I see my folders, (awesome)
[3] I do *not* see any aliases, folders or files, (not good)
[4] I also do not see my network mounted NAS drive in the sidebar

**Expected behavior**
Ideally any folder or alias I can see on the Desktop should be represented in uwp.  Manually entering "\\Diskstation" into the path does nothing, uwp says "this folder is empty", then crashes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 build 18363.836
 - App version: 0.9.0.0

**Additional context**
Probably the most reasonable file manager on windows I've ever seen.  If you get column view or even image previews working (psd previews etc) then, just wow.

**Comment by lampenlampen** [comment] 2020-05-26 20:13
This is a known bug, that network drives appear empty (#642).

**Comment by yaichenbaum** [comment] 2020-05-26 22:34
@psdcovers Thank you for the kind words 😃. Can you check if manually navigating to your drives work?

**Comment by psdcovers** [comment] 2020-05-28 15:38
> @psdcovers Thank you for the kind words smiley. Can you check if manually navigating to your drives work?

No, if I type the path to a mounted drive or to the alias on my desktop I just get an invalid item error.

**Comment by duke7553** [comment] 2020-06-11 04:04
Duplicate of #642 

Thanks for the first impressions! We know this is an important item to fix for users. To be notified when the solution is available, please subscribe to the original item linked above.

**Closed by duke7553** 2020-06-11 04:04 UTC
Labels: bug
