### ISSUE TITLE
iCloud support

### ISSUE THREAD

**Issue by p0risonpupu** [files-community/files-uwp#1399] opened 2020-07-11 21:57 UTC
Hi Guys, 
The beta is beautifully designed and I would love to switch, but is there no Icloud drive support?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903 18362.175]
 - App version: [v0.11.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by yaichenbaum** [comment] 2020-07-12 02:13
@p0risonpupu Have you tried navigating to iCloud and pinning the location to the sidebar?

**Comment by Jaiganeshkumaran** [comment] 2020-07-12 06:03
Duplicate of #242.

**Comment by yaichenbaum** [comment] 2020-07-17 04:15
Merging with #242.

**Closed by yaichenbaum** 2020-07-17 04:15 UTC
Labels: bug, feature_request, needs-triage
