### ISSUE TITLE
append tags to files/folders via cookies/system.ini

### ISSUE THREAD

**Issue by chuchanpr** [files-community/files-uwp#1539] opened 2020-07-22 17:06 UTC
**Is your feature request related to a problem? 
A clear and concise description of what the problem is. append tags to files/folders via cookies/system.ini

**Describe the solution you'd like**
A clear and concise description of what you want to happen. append tags to files/folders via cookies/system.ini This will allow, searching / reaching / sorting files easily

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. - no solution in windows yet

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

![image](https://user-images.githubusercontent.com/4193718/88206350-bc3e7c00-cc6b-11ea-91a9-b5c42e2c8e15.png)

**Comment by duke7553** [comment] 2020-07-22 20:10
Duplicate of #1161

**Closed by duke7553** 2020-07-22 20:10 UTC
Labels: enhancement, feature_request, needs-triage
