### ISSUE TITLE
Crash when opening a new tab when flyout is disabled

### ISSUE THREAD

**Issue by generalguy41** [files-community/files-uwp#1709] opened 2020-08-12 12:40 UTC
**Describe the bug**
Program will crash when trying to open a new tab when the multitasking flyout is disabled.

**To Reproduce**
1. Disable multitasking flyout
2. Try to open a new tab

**Expected behavior**
Program will not crash

**Screenshots**
![ezgif-6-c992175ca4f6](https://user-images.githubusercontent.com/8879244/90015587-cce47f80-dc76-11ea-8ace-3b7ddb309e83.gif)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 2004 20185.1000]
 - App version: [v0.13.0.0]

**Additional context**
[debug.txt](https://github.com/files-community/files-uwp/files/5062665/debug.txt)
[debug_fulltrust.txt](https://github.com/files-community/files-uwp/files/5062674/debug_fulltrust.txt)

**Comment by XPoppyX** [comment] 2020-08-12 12:53
Duplicate of #1641

**Closed** 2020-08-12 12:54 UTC
Labels: bug, needs-triage
