### ISSUE TITLE
 I'm having trouble opening file using touch

### ISSUE THREAD

**Issue by 00SAMU** [files-community/files-uwp#811] opened 2020-05-19 16:45 UTC
**Describe the bug**
On my surface laptop 3, when i try to open a file (such as an image) using touch, i try to simulate a "double click", like when i open a file normally usning the touchpad or the mouse, but the most of the times the file does not open, due to a bad timing calibration between the two touches i think (but i'm not sure). Sometimes the files opens if i touch 3 times really quickly, but is really uneasy and sometimes doesn't even work.

AND if i hold the touch on a file for a few seconds, the application freezes or crashes

**To Reproduce**
Open Files UWP - Preview
to 1st problem - Open a file or a directory using the touch
to 2nd problem - Hold the touch on a file for a few seconds

**Expected behavior**
I expect that the file opens when i touch only two times on it, AND i do not expect that the application crashes/freezes when i hold the touch on a file for a few seconds

**Desktop (please complete the following information):**
 - OS Version: 1909 (build 18363.836)
 - App version: [v0.8.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?
Yes, the problems occour again after restarting the app, but the first problem sometimes does not occur when i open directories only, but it is quite unpredictable.

Sorry for my bad English, however this is my first bug report on Git-Hub

**Comment by duke7553** [comment] 2020-05-26 01:54
Duplicate of #734

**Closed by duke7553** 2020-05-26 01:54 UTC
Labels: bug, needs-triage
