### ISSUE TITLE
Smart Layout mode

### ISSUE THREAD

**Issue by Darhagonable** [files-community/files-uwp#915] opened 2020-06-04 21:58 UTC
I think it would be great if the layout mode could be smart and depend on whats in the location.
I at least want list view when there's just normal files and folders but whenever there is an image anywhere i want it to use grid view (in my case small).
So my idea is that one would be able to select the layout mode depending on if there is an image in the location or not.

**Comment by Jaiganeshkumaran** [comment] 2020-06-05 07:45
Duplicate of #530

**Comment by yaichenbaum** [comment] 2020-06-05 13:32
Merging with #530.

**Closed by yaichenbaum** 2020-06-05 13:32 UTC
Labels: duplicate, enhancement
