### ISSUE TITLE
Selection with mouse drag

### ISSUE THREAD

**Issue by antnauman** [files-community/files-uwp#1738] opened 2020-08-14 08:55 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by antnauman** [comment] 2020-08-14 08:57
Please make able to select file/folders using mouse click and drag.

**Comment by Jaiganeshkumaran** [comment] 2020-08-14 08:59
@antnauman Duplicate of #94

**Closed** 2020-08-14 12:07 UTC
Labels: duplicate
