### ISSUE TITLE
Files UWP can't difference between Onedrive personal and Onedrive for Business

### ISSUE THREAD

**Issue by xtprion** [files-community/files-uwp#1460] opened 2020-07-15 04:11 UTC
**Describe the bug**
OneDrive sidebar only navigate to one account

**To Reproduce**
1. Go to Onedrive
2. See error

**Expected behavior**
It should have more than one onedrive, like personal onedrive, business onedrive etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/46372297/87502368-9a516200-c68b-11ea-8cf5-49f3f2cd80ed.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 Insider Preview Build 20161.1000]
 - App version: [v0.12.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app? YES

**Comment by Jaiganeshkumaran** [comment] 2020-07-15 04:38
Duplicate of #16

**Closed** 2020-07-15 11:55 UTC
Labels: bug, needs-triage
