### ISSUE TITLE
Two OneDrive accounts login in suggestions

### ISSUE THREAD

**Issue by WallerGeque** [files-community/files-uwp#1864] opened 2020-09-03 06:10 UTC
When two onedrives log in, we can't view their folders separately at the same time. You can only access one folder.

**Comment by Jaiganeshkumaran** [comment] 2020-09-03 06:57
@WallerGeque Only one account is shown on the sidebar however you can access another by typing the location on the navigation path box.

**Comment by yaichenbaum** [comment] 2020-09-03 13:25
Duplicate of #1794.

**Closed by yaichenbaum** 2020-09-03 13:25 UTC
Labels: bug, feature_request, needs-triage
