### ISSUE TITLE
Buggy touch behaviour in "details" view

### ISSUE THREAD

**Issue by Serarg95** [files-community/files-uwp#974] opened 2020-06-10 07:26 UTC
When I use the app in the default "details" view, sometimes I try double finger click (it should be one click with finger but i guess u are already considering this) to open a folder and it doesnt work. That bug never happens if I change to "icons" view.

App version: 0.9.2.0
Windows version: Windows 10 2004 (19041.264)

**Comment by Jaiganeshkumaran** [comment] 2020-06-11 06:48
Duplicate of #734

**Comment by yaichenbaum** [comment] 2020-06-22 00:20
Merging with #734.

**Closed by yaichenbaum** 2020-06-22 00:20 UTC
Labels: bug
