### ISSUE TITLE
Network Mapped Drive Access

### ISSUE THREAD

**Issue by harphoonj** [files-community/files-uwp#1267] opened 2020-06-27 16:00 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'SideBar Drive Lift
2. Click on '..Network Mapped Drive(LetterPath).'
3. Files UWP will say "this folder is empty"

**Expected behavior**
When opening network drive path, files and folders stored on drive should be visible in explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/11496846/85926454-6df8b180-b854-11ea-8c5f-abf2204d57b8.png)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 pro 2004 19041.329]
 - App version: [v0.10.2.0]

**Additional context**
Add any other context about the problem here. Does this problem occur again after restarting the app?

**Comment by duke7553** [comment] 2020-06-27 16:11
Duplicate of #642

**Closed by duke7553** 2020-06-27 16:11 UTC
Labels: bug, needs-triage
