### ISSUE TITLE
Rename of file opens the file

### ISSUE THREAD

**Issue by xumepoc** [files-community/files-uwp#1309] opened 2020-06-30 08:55 UTC
When the experimental features to rename a file is turned off and you want to rename a .docx file from the contextual menu, instead to rename the file, Files UWP opens the file.

Steps to reproduce the behaviour:
1. Disable "Double tab to rename a files"
2. Select a .docx file.
3. Right click and choose Rename
4. The file is opened instead to rename it.

**Expected behaviour**
Choosing a Rename option in the contextual menu should rename the file :) 

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 18363.900
 - App version: v0.11.0.0

**Comment by XPoppyX** [comment] 2020-06-30 13:56
Duplicate of #306 #651

**Closed** 2020-06-30 14:42 UTC
Labels: bug, needs-triage
